// Fixed menu items — images and names never change
// Only PRICE and AVAILABILITY are editable from Admin Dashboard
// Taken from popular Indian restaurant menus

export const FIXED_MENU_ITEMS = [

  // ═══════════════════════════════════════════════════════
  //  STARTERS  (6 items)
  // ═══════════════════════════════════════════════════════
  {
    fixedId: 'starter-1',
    name: 'Paneer Tikka',
    category: 'Starters',
    description: 'Succulent cottage cheese cubes marinated in spiced yogurt, grilled to perfection in a tandoor. Smoky, tender and utterly irresistible.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'Low',
  },
  {
    fixedId: 'starter-2',
    name: 'Chicken Seekh Kebab',
    category: 'Starters',
    description: 'Minced chicken blended with aromatic spices, shaped on skewers and charcoal-grilled until golden. Served with mint chutney.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80',
    is_vegetarian: false,
    is_spicy: true,
    spicy: 'Medium',
  },
  {
    fixedId: 'starter-3',
    name: 'Samosa Chaat',
    category: 'Starters',
    description: 'Crispy golden samosas topped with tangy tamarind chutney, fresh yogurt, sev and pomegranate seeds. A street food classic elevated.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    is_vegetarian: true,
    is_spicy: true,
    spicy: 'Medium',
  },
  {
    fixedId: 'starter-4',
    name: 'Aloo Tikki',
    category: 'Starters',
    description: 'Crispy spiced potato patties pan-fried golden, served with green chutney and tamarind sauce. A beloved North Indian street snack.',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'Low',
  },
  {
    fixedId: 'starter-5',
    name: 'Tandoori Chicken',
    category: 'Starters',
    description: 'Whole chicken marinated overnight in yogurt and spices, roasted in a traditional clay tandoor. Juicy inside, charred outside.',
    image: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=800&q=80',
    is_vegetarian: false,
    is_spicy: true,
    spicy: 'Medium',
  },
  {
    fixedId: 'starter-6',
    name: 'Onion Bhaji',
    category: 'Starters',
    description: 'Crispy golden fritters made with sliced onions, gram flour and a blend of spices. Light, crunchy and absolutely addictive.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'Low',
  },

  // ═══════════════════════════════════════════════════════
  //  MAIN COURSE  (8 items)
  // ═══════════════════════════════════════════════════════
  {
    fixedId: 'main-1',
    name: 'Handi Mutton',
    category: 'Main Course',
    description: 'Slow-cooked tender mutton in a traditional clay pot with whole spices, caramelized onions and rich brown gravy. A royal recipe.',
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=800&q=80',
    is_vegetarian: false,
    is_spicy: true,
    spicy: 'High',
  },
  {
    fixedId: 'main-2',
    name: 'Butter Chicken',
    category: 'Main Course',
    description: "Tender chicken in a velvety tomato-butter sauce with cream and aromatic spices. India's most beloved curry, perfected over generations.",
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80',
    is_vegetarian: false,
    is_spicy: false,
    spicy: 'Low',
  },
  {
    fixedId: 'main-3',
    name: 'Dal Makhani',
    category: 'Main Course',
    description: 'Black lentils slow-cooked overnight with butter, cream and tomatoes. Rich, indulgent and deeply satisfying — a Punjabi treasure.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'main-4',
    name: 'Paneer Butter Masala',
    category: 'Main Course',
    description: 'Cottage cheese cubes simmered in a rich, creamy tomato-cashew gravy. Mildly spiced and deeply flavourful — vegetarian comfort food.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'Low',
  },
  {
    fixedId: 'main-5',
    name: 'Chicken Tikka Masala',
    category: 'Main Course',
    description: 'Grilled chicken tikka pieces cooked in a spiced onion-tomato masala with cream. Bold, smoky and utterly satisfying.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    is_vegetarian: false,
    is_spicy: true,
    spicy: 'Medium',
  },
  {
    fixedId: 'main-6',
    name: 'Palak Paneer',
    category: 'Main Course',
    description: 'Fresh cottage cheese in a vibrant, velvety spinach gravy seasoned with garlic, ginger and warm spices. Nutritious and delicious.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'Low',
  },
  {
    fixedId: 'main-7',
    name: 'Rogan Josh',
    category: 'Main Course',
    description: 'Slow-braised lamb in a Kashmiri sauce of whole spices, dried chilies and aromatics. Deeply fragrant and intensely flavourful.',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80',
    is_vegetarian: false,
    is_spicy: true,
    spicy: 'High',
  },
  {
    fixedId: 'main-8',
    name: 'Chana Masala',
    category: 'Main Course',
    description: 'Hearty chickpeas cooked in a tangy, spiced tomato-onion gravy. A Punjabi classic that is both filling and full of bold flavour.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    is_vegetarian: true,
    is_spicy: true,
    spicy: 'Medium',
  },

  // ═══════════════════════════════════════════════════════
  //  BREADS & RICE  (4 items)
  // ═══════════════════════════════════════════════════════
  {
    fixedId: 'bread-1',
    name: 'Garlic Naan',
    category: 'Breads & Rice',
    description: 'Soft, fluffy leavened bread baked in a tandoor, brushed with garlic butter and fresh coriander. Perfect to scoop up any curry.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'bread-2',
    name: 'Hyderabadi Biryani',
    category: 'Breads & Rice',
    description: 'Fragrant basmati rice layered with spiced mutton, saffron, caramelized onions and fresh mint. Slow-cooked in a sealed pot for peak flavour.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    is_vegetarian: false,
    is_spicy: true,
    spicy: 'Medium',
  },
  {
    fixedId: 'bread-3',
    name: 'Jeera Rice',
    category: 'Breads & Rice',
    description: 'Fluffy basmati rice tempered with cumin seeds, ghee and whole spices. A simple, aromatic accompaniment that pairs with any curry.',
    image: 'https://images.unsplash.com/photo-1694849789395-a74e95a26905?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'bread-4',
    name: 'Stuffed Paratha',
    category: 'Breads & Rice',
    description: 'Whole wheat flatbread stuffed with spiced mashed potato, pan-fried with butter. Served with yogurt and pickle — a Punjabi breakfast favourite.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'Low',
  },

  // ═══════════════════════════════════════════════════════
  //  DESSERTS  (5 items)
  // ═══════════════════════════════════════════════════════
  {
    fixedId: 'dessert-1',
    name: 'Gulab Jamun',
    category: 'Desserts',
    description: "Soft milk-solid dumplings fried golden and soaked in rose-scented sugar syrup. Served warm — India's most beloved sweet.",
    image: 'https://images.unsplash.com/photo-1666450555768-192ddb2a66ea?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'dessert-2',
    name: 'Kulfi Ice Cream',
    category: 'Desserts',
    description: 'Traditional Indian ice cream made with reduced milk, saffron, pistachios and cardamom. Denser and creamier than regular ice cream.',
    image: 'https://images.unsplash.com/photo-1560008511-11c63416e52d?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'dessert-3',
    name: 'Rasgulla',
    category: 'Desserts',
    description: 'Spongy cottage cheese balls cooked in light sugar syrup. Delicate, airy and melt-in-your-mouth — a Bengali classic.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'dessert-4',
    name: 'Gajar Ka Halwa',
    category: 'Desserts',
    description: 'Slow-cooked grated carrot pudding with ghee, sugar, milk and cardamom, topped with nuts. A warming winter delicacy from North India.',
    image: 'https://images.unsplash.com/photo-1548364538-b7408a6e0e4b?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'dessert-5',
    name: 'Kheer',
    category: 'Desserts',
    description: 'Creamy rice pudding slow-cooked in full-fat milk with sugar, cardamom, saffron and topped with almonds and pistachios.',
    image: 'https://images.unsplash.com/photo-1571167014537-ebb6a90ce5f4?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },

  // ═══════════════════════════════════════════════════════
  //  DRINKS  (3 items)
  // ═══════════════════════════════════════════════════════
  {
    fixedId: 'drink-1',
    name: 'Mango Lassi',
    category: 'Drinks',
    description: 'Cool, creamy yogurt blended with sweet Alphonso mango pulp. The perfect cooling companion to spicy Indian food.',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'drink-2',
    name: 'Masala Chai',
    category: 'Drinks',
    description: 'Strong Assam tea brewed with ginger, cardamom, cloves and cinnamon, finished with full-fat milk. India in a cup.',
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
  {
    fixedId: 'drink-3',
    name: 'Sweet Lassi',
    category: 'Drinks',
    description: 'Chilled yogurt drink sweetened with sugar and flavoured with rose water and a pinch of cardamom. Refreshing and soothing.',
    image: 'https://images.unsplash.com/photo-1608198399988-341fd2acd575?w=800&q=80',
    is_vegetarian: true,
    is_spicy: false,
    spicy: 'None',
  },
];

// All unique categories derived from the items above
export const FIXED_CATEGORIES = [...new Set(FIXED_MENU_ITEMS.map(i => i.category))];